name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo

      - name: Build
        run: cargo build --release --features deploy

      - name: Copy files
        run: |
          mkdir release
          cp target/release/vsm release/
          cp target/release/vsm_generator release/
      - name: Compress files
        run: tar -czvf Linux-amd64.tar.gz release

      - name: Get version
        run: echo "version=v0.1.0-alpha${{ github.run_number }}" >> $GITHUB_ENV 

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.version }}
          tag_name: ${{ env.version }}
          prerelease: true
          files: Linux-amd64.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
