name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo

      - name: Use LLD
        run: echo -en "[target.x86_64-unknown-linux-gnu]\nlinker = \"clang\"\nrustflags = [\"-C\", \"link-arg=-fuse-ld=lld\"]\n" > ~/.cargo/config.toml
      - name: Build
        run: cargo build --release --features deploy

      - name: Enforce cache update
        run: |
          STATE_CACHE_KEY="${{ runner.os }}-cargo"
          echo "STATE_CACHE_KEY=${STATE_CACHE_KEY}" >> $GITHUB_ENV

      - name: Copy files
        run: |
          mkdir release
          cp target/release/vsm release/
          cp target/release/vsm_generator release/
          cp target/release/vsm_updater release/
      - name: Compress files
        working-directory: ./release
        run: tar -czvf ../Linux-amd64.tar.gz *

      - name: Get version
        run: echo "version=v0.1.0-alpha${{ github.run_number }}" >> $GITHUB_ENV 

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.version }}
          tag: ${{ env.version }}
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "Linux-amd64.tar.gz"
